server:
  port: ${APPLICATION_PORT:8765}
spring:
  application:
    name: @project.artifactId@
    version: @project.version@
    fullname: @project.name@
logging:
  level:
    org.springframework: ERROR
    com.tabeldata: ${LOG_LEVEL:DEBUG}
  file:
    name: ${LOG_LOCATION:${spring.application.name}.log}
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
    fetch-registry: true
zuul:
  sensitive-headers: Cookie,Set-Cookie
  ignored-services: '*'
  routes:
    wilayah-service:
      path: /spring-cloud-wilayah-service/**
      serviceId: spring-cloud-wilayah-service
      stripPrefix: false
  host:
    connect-timeout-millis: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
  metrics:
    enabled: true
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
