version: '3.7'
services:
  mysql:
    image: repository.dimas-maryanto.com:8086/mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=wilayah_service
      - MYSQL_PASSWORD=wilayah_service
      - MYSQL_DATABASE=wilayah_service
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring-cloud-network
  postgres:
    image: repository.dimas-maryanto.com:8086/postgres:12.1
    environment:
      - POSTGRES_PASSWORD=nasabah_service
      - POSTGRES_USER=nasabah_service
      - POSTGRES_DB=nasabah_service
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-cloud-network
volumes:
  mysql_data:
  postgres_data:
networks:
  spring-cloud-network:
