server:
  port: ${APPLICATION_PORT:8761}
spring:
  application:
    name: @project.artifactId@
logging:
  level:
    org.springframework: ERROR
    com.maryanto.dimas.example: ${LOG_LEVEL:DEBUG}
  file:
    name: ${LOG_LOCATION:${spring.application.name}.log}
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
hystrix:
  metrics:
    enabled: true