server:
  port: ${APPLICATION_PORT:8020}
  servlet:
    context-path: /@project.artifactId@
# spring configuration
spring:
  application:
    name: @project.artifactId@
    version: @project.version@
    fullname: @project.name@
  mvc:
    dispatch-options-request: true
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:nasabah_service}
    username: ${DATABASE_USER:nasabah_service}
    password: ${DATABASE_PASSWORD:nasabah_service}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        id:
          new_generator_mappings: false
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        globally_quoted_identifiers: true
    database: postgresql
  flyway:
    encoding: UTF-8
    enabled: ${FLYWAY_ENABLED:false}
    baseline-on-migrate: true
    check-location: true
    locations: classpath:/db/migration
    clean-disabled: false
    clean-on-validation-error: true
    connect-retries: 2
logging:
  level:
    org.springframework: ERROR
    com.tabeldata: DEBUG
  file:
    name: ${LOG_LOCATION:${spring.application.name}.log}
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
    fetch-registry: true
